// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package gamma_api

import "strconv"

type SearchResultCode int8

const (
	SearchResultCodeSUCCESS           SearchResultCode = 0
	SearchResultCodeINDEX_NOT_TRAINED SearchResultCode = 1
	SearchResultCodeSEARCH_ERROR      SearchResultCode = 2
)

var EnumNamesSearchResultCode = map[SearchResultCode]string{
	SearchResultCodeSUCCESS:           "SUCCESS",
	SearchResultCodeINDEX_NOT_TRAINED: "INDEX_NOT_TRAINED",
	SearchResultCodeSEARCH_ERROR:      "SEARCH_ERROR",
}

var EnumValuesSearchResultCode = map[string]SearchResultCode{
	"SUCCESS":           SearchResultCodeSUCCESS,
	"INDEX_NOT_TRAINED": SearchResultCodeINDEX_NOT_TRAINED,
	"SEARCH_ERROR":      SearchResultCodeSEARCH_ERROR,
}

func (v SearchResultCode) String() string {
	if s, ok := EnumNamesSearchResultCode[v]; ok {
		return s
	}
	return "SearchResultCode(" + strconv.FormatInt(int64(v), 10) + ")"
}
