# automatically generated by the FlatBuffers compiler, do not modify

# namespace: gamma_api

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Config(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Config()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsConfig(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Config
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Config
    def Path(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Config
    def LogDir(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Config
    def CacheInfos(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from gamma_api.CacheInfo import CacheInfo
            obj = CacheInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Config
    def CacheInfosLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Config
    def CacheInfosIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def Start(builder): builder.StartObject(3)
def ConfigStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddPath(builder, path): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(path), 0)
def ConfigAddPath(builder, path):
    """This method is deprecated. Please switch to AddPath."""
    return AddPath(builder, path)
def AddLogDir(builder, logDir): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(logDir), 0)
def ConfigAddLogDir(builder, logDir):
    """This method is deprecated. Please switch to AddLogDir."""
    return AddLogDir(builder, logDir)
def AddCacheInfos(builder, cacheInfos): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(cacheInfos), 0)
def ConfigAddCacheInfos(builder, cacheInfos):
    """This method is deprecated. Please switch to AddCacheInfos."""
    return AddCacheInfos(builder, cacheInfos)
def StartCacheInfosVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ConfigStartCacheInfosVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartCacheInfosVector(builder, numElems)
def End(builder): return builder.EndObject()
def ConfigEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)