# automatically generated by the FlatBuffers compiler, do not modify

# namespace: gamma_api

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Response(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Response()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Response
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Response
    def Results(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from gamma_api.SearchResult import SearchResult
            obj = SearchResult()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Response
    def ResultsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Response
    def ResultsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # Response
    def OnlineLogMessage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Start(builder): builder.StartObject(2)
def ResponseStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddResults(builder, results): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(results), 0)
def ResponseAddResults(builder, results):
    """This method is deprecated. Please switch to AddResults."""
    return AddResults(builder, results)
def StartResultsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ResponseStartResultsVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartResultsVector(builder, numElems)
def AddOnlineLogMessage(builder, onlineLogMessage): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(onlineLogMessage), 0)
def ResponseAddOnlineLogMessage(builder, onlineLogMessage):
    """This method is deprecated. Please switch to AddOnlineLogMessage."""
    return AddOnlineLogMessage(builder, onlineLogMessage)
def End(builder): return builder.EndObject()
def ResponseEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)