# automatically generated by the FlatBuffers compiler, do not modify

# namespace: gamma_api

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Table(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Table()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Table
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Table
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Table
    def Fields(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from gamma_api.FieldInfo import FieldInfo
            obj = FieldInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Table
    def FieldsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Table
    def FieldsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # Table
    def VectorsInfo(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from gamma_api.VectorInfo import VectorInfo
            obj = VectorInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Table
    def VectorsInfoLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Table
    def VectorsInfoIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # Table
    def IndexingSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Table
    def CompressMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Table
    def RetrievalType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Table
    def RetrievalParam(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Table
    def RetrievalTypes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # Table
    def RetrievalTypesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Table
    def RetrievalTypesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # Table
    def RetrievalParams(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # Table
    def RetrievalParamsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Table
    def RetrievalParamsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

def Start(builder): builder.StartObject(9)
def TableStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddName(builder, name): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def TableAddName(builder, name):
    """This method is deprecated. Please switch to AddName."""
    return AddName(builder, name)
def AddFields(builder, fields): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(fields), 0)
def TableAddFields(builder, fields):
    """This method is deprecated. Please switch to AddFields."""
    return AddFields(builder, fields)
def StartFieldsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def TableStartFieldsVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartFieldsVector(builder, numElems)
def AddVectorsInfo(builder, vectorsInfo): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(vectorsInfo), 0)
def TableAddVectorsInfo(builder, vectorsInfo):
    """This method is deprecated. Please switch to AddVectorsInfo."""
    return AddVectorsInfo(builder, vectorsInfo)
def StartVectorsInfoVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def TableStartVectorsInfoVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartVectorsInfoVector(builder, numElems)
def AddIndexingSize(builder, indexingSize): builder.PrependInt32Slot(3, indexingSize, 0)
def TableAddIndexingSize(builder, indexingSize):
    """This method is deprecated. Please switch to AddIndexingSize."""
    return AddIndexingSize(builder, indexingSize)
def AddCompressMode(builder, compressMode): builder.PrependInt32Slot(4, compressMode, 0)
def TableAddCompressMode(builder, compressMode):
    """This method is deprecated. Please switch to AddCompressMode."""
    return AddCompressMode(builder, compressMode)
def AddRetrievalType(builder, retrievalType): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(retrievalType), 0)
def TableAddRetrievalType(builder, retrievalType):
    """This method is deprecated. Please switch to AddRetrievalType."""
    return AddRetrievalType(builder, retrievalType)
def AddRetrievalParam(builder, retrievalParam): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(retrievalParam), 0)
def TableAddRetrievalParam(builder, retrievalParam):
    """This method is deprecated. Please switch to AddRetrievalParam."""
    return AddRetrievalParam(builder, retrievalParam)
def AddRetrievalTypes(builder, retrievalTypes): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(retrievalTypes), 0)
def TableAddRetrievalTypes(builder, retrievalTypes):
    """This method is deprecated. Please switch to AddRetrievalTypes."""
    return AddRetrievalTypes(builder, retrievalTypes)
def StartRetrievalTypesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def TableStartRetrievalTypesVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartRetrievalTypesVector(builder, numElems)
def AddRetrievalParams(builder, retrievalParams): builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(retrievalParams), 0)
def TableAddRetrievalParams(builder, retrievalParams):
    """This method is deprecated. Please switch to AddRetrievalParams."""
    return AddRetrievalParams(builder, retrievalParams)
def StartRetrievalParamsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def TableStartRetrievalParamsVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartRetrievalParamsVector(builder, numElems)
def End(builder): return builder.EndObject()
def TableEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)