version: '3'
services:
  awadb:
    image: ljeagle/awadb:v0.14
    restart: always
  awadb_proxy:
    depends_on:
      - awadb
    image: ljeagle/awadb_proxy:v0.13
    ports:
      - 8080:8080
      - 50005:50005
    restart: always
