# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from awadb.py_idl import awadb_pb2 as awadb__pb2


class AwaDBServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/awadb_grpc.AwaDBServer/Create',
                request_serializer=awadb__pb2.DBMeta.SerializeToString,
                response_deserializer=awadb__pb2.ResponseStatus.FromString,
                )
        self.DropDB = channel.unary_unary(
                '/awadb_grpc.AwaDBServer/DropDB',
                request_serializer=awadb__pb2.DBName.SerializeToString,
                response_deserializer=awadb__pb2.ResponseStatus.FromString,
                )
        self.DropTable = channel.unary_unary(
                '/awadb_grpc.AwaDBServer/DropTable',
                request_serializer=awadb__pb2.TableName.SerializeToString,
                response_deserializer=awadb__pb2.ResponseStatus.FromString,
                )
        self.ShowTables = channel.unary_unary(
                '/awadb_grpc.AwaDBServer/ShowTables',
                request_serializer=awadb__pb2.DBName.SerializeToString,
                response_deserializer=awadb__pb2.TableNames.FromString,
                )
        self.DescTable = channel.unary_unary(
                '/awadb_grpc.AwaDBServer/DescTable',
                request_serializer=awadb__pb2.TableName.SerializeToString,
                response_deserializer=awadb__pb2.TableMeta.FromString,
                )
        self.AddFields = channel.unary_unary(
                '/awadb_grpc.AwaDBServer/AddFields',
                request_serializer=awadb__pb2.DBMeta.SerializeToString,
                response_deserializer=awadb__pb2.ResponseStatus.FromString,
                )
        self.AddOrUpdate = channel.unary_unary(
                '/awadb_grpc.AwaDBServer/AddOrUpdate',
                request_serializer=awadb__pb2.Documents.SerializeToString,
                response_deserializer=awadb__pb2.ResponseStatus.FromString,
                )
        self.Get = channel.unary_unary(
                '/awadb_grpc.AwaDBServer/Get',
                request_serializer=awadb__pb2.DocCondition.SerializeToString,
                response_deserializer=awadb__pb2.Documents.FromString,
                )
        self.Search = channel.unary_unary(
                '/awadb_grpc.AwaDBServer/Search',
                request_serializer=awadb__pb2.SearchRequest.SerializeToString,
                response_deserializer=awadb__pb2.SearchResponse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/awadb_grpc.AwaDBServer/Delete',
                request_serializer=awadb__pb2.DocCondition.SerializeToString,
                response_deserializer=awadb__pb2.ResponseStatus.FromString,
                )


class AwaDBServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropDB(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowTables(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddFields(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddOrUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AwaDBServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=awadb__pb2.DBMeta.FromString,
                    response_serializer=awadb__pb2.ResponseStatus.SerializeToString,
            ),
            'DropDB': grpc.unary_unary_rpc_method_handler(
                    servicer.DropDB,
                    request_deserializer=awadb__pb2.DBName.FromString,
                    response_serializer=awadb__pb2.ResponseStatus.SerializeToString,
            ),
            'DropTable': grpc.unary_unary_rpc_method_handler(
                    servicer.DropTable,
                    request_deserializer=awadb__pb2.TableName.FromString,
                    response_serializer=awadb__pb2.ResponseStatus.SerializeToString,
            ),
            'ShowTables': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowTables,
                    request_deserializer=awadb__pb2.DBName.FromString,
                    response_serializer=awadb__pb2.TableNames.SerializeToString,
            ),
            'DescTable': grpc.unary_unary_rpc_method_handler(
                    servicer.DescTable,
                    request_deserializer=awadb__pb2.TableName.FromString,
                    response_serializer=awadb__pb2.TableMeta.SerializeToString,
            ),
            'AddFields': grpc.unary_unary_rpc_method_handler(
                    servicer.AddFields,
                    request_deserializer=awadb__pb2.DBMeta.FromString,
                    response_serializer=awadb__pb2.ResponseStatus.SerializeToString,
            ),
            'AddOrUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.AddOrUpdate,
                    request_deserializer=awadb__pb2.Documents.FromString,
                    response_serializer=awadb__pb2.ResponseStatus.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=awadb__pb2.DocCondition.FromString,
                    response_serializer=awadb__pb2.Documents.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=awadb__pb2.SearchRequest.FromString,
                    response_serializer=awadb__pb2.SearchResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=awadb__pb2.DocCondition.FromString,
                    response_serializer=awadb__pb2.ResponseStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'awadb_grpc.AwaDBServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AwaDBServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/awadb_grpc.AwaDBServer/Create',
            awadb__pb2.DBMeta.SerializeToString,
            awadb__pb2.ResponseStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DropDB(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/awadb_grpc.AwaDBServer/DropDB',
            awadb__pb2.DBName.SerializeToString,
            awadb__pb2.ResponseStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DropTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/awadb_grpc.AwaDBServer/DropTable',
            awadb__pb2.TableName.SerializeToString,
            awadb__pb2.ResponseStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ShowTables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/awadb_grpc.AwaDBServer/ShowTables',
            awadb__pb2.DBName.SerializeToString,
            awadb__pb2.TableNames.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DescTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/awadb_grpc.AwaDBServer/DescTable',
            awadb__pb2.TableName.SerializeToString,
            awadb__pb2.TableMeta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddFields(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/awadb_grpc.AwaDBServer/AddFields',
            awadb__pb2.DBMeta.SerializeToString,
            awadb__pb2.ResponseStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddOrUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/awadb_grpc.AwaDBServer/AddOrUpdate',
            awadb__pb2.Documents.SerializeToString,
            awadb__pb2.ResponseStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/awadb_grpc.AwaDBServer/Get',
            awadb__pb2.DocCondition.SerializeToString,
            awadb__pb2.Documents.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/awadb_grpc.AwaDBServer/Search',
            awadb__pb2.SearchRequest.SerializeToString,
            awadb__pb2.SearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/awadb_grpc.AwaDBServer/Delete',
            awadb__pb2.DocCondition.SerializeToString,
            awadb__pb2.ResponseStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
